import mods.itemstages.ItemStages;

ItemStages.createModRestriction("alchemistry", "banitem");

ItemStages.restrict(<item:industrialforegoing:latex_processing_unit>, "banitem");
ItemStages.restrict(<item:exmachinis:gold_upgrade>, "banitem");
ItemStages.restrict(<item:exmachinis:diamond_upgrade>, "banitem");
ItemStages.restrict(<item:exmachinis:netherite_upgrade>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_drain>.withTag({texture: "industrialforegoing:laser_lens15"}), "banitem");
ItemStages.restrict(<item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_cracked_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_cobble"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_paver"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_fancy_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_triangle_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_cracked_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_cobble"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_paver"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_fancy_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_triangle_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_cracked_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_cobble"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_paver"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_fancy_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_stone>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_cobble>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_paver>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_bricks>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_cracked_bricks>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_fancy_bricks>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_triangle_bricks>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_triangle_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_stone>, "banitem");
ItemStages.restrict(<item:tconstruct:polished_scorched_stone>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_bricks>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_road>, "banitem");
ItemStages.restrict(<item:tconstruct:chiseled_scorched_bricks>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:scorched_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:polished_scorched_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:scorched_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:scorched_road"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:chiseled_scorched_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:scorched_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:polished_scorched_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:scorched_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:scorched_road"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:chiseled_scorched_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:scorched_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:polished_scorched_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:scorched_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:scorched_road"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:chiseled_scorched_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_fuel_tank>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_fuel_gauge>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_ingot_tank>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_ingot_gauge>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_lantern>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_faucet>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_channel>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_basin>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_table>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_fuel_tank>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_fuel_gauge>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_ingot_tank>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_ingot_gauge>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_lantern>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_faucet>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_channel>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_basin>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_table>, "banitem");
ItemStages.restrict(<item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_cracked_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_cobble"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_paver"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_fancy_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_triangle_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:scorched_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:polished_scorched_stone"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:scorched_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:scorched_road"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:chiseled_scorched_bricks"}), "banitem"); 
ItemStages.restrict(<item:tconstruct:seared_melter>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_heater>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_alloyer>, "banitem");
ItemStages.restrict(<item:thermal:satchel>, "banitem");
ItemStages.restrict(<item:exmachinis:flux_compactor>, "banitem");
ItemStages.restrict(<item:mekanism:basic_logistical_transporter>, "banitem");
ItemStages.restrict(<item:mekanism:advanced_logistical_transporter>, "banitem");
ItemStages.restrict(<item:mekanism:elite_logistical_transporter>, "banitem");
ItemStages.restrict(<item:mekanism:ultimate_logistical_transporter>, "banitem");
ItemStages.restrict(<item:ae2:quantum_link>, "banitem");
ItemStages.restrict(<item:ae2:quantum_ring>, "banitem");
ItemStages.restrict(<item:industrialforegoing:mechanical_dirt>, "banitem");
ItemStages.restrict(<item:tconstruct:efln_ball>, "banitem");
ItemStages.restrict(<item:tconstruct:scorched_brick>, "banitem");
ItemStages.restrict(<item:thermal:explosive_grenade>, "banitem");
ItemStages.restrict(<item:thermal:fire_grenade>, "banitem");
ItemStages.restrict(<item:thermal:ice_grenade>, "banitem");
ItemStages.restrict(<item:thermal:lightning_grenade>, "banitem");
ItemStages.restrict(<item:thermal:earth_grenade>, "banitem");
ItemStages.restrict(<item:thermal:ender_grenade>, "banitem");
ItemStages.restrict(<item:thermal:glowstone_grenade>, "banitem");
ItemStages.restrict(<item:thermal:redstone_grenade>, "banitem");
ItemStages.restrict(<item:thermal:slime_grenade>, "banitem");
ItemStages.restrict(<item:thermal:phyto_grenade>, "banitem");
ItemStages.restrict(<item:thermal:fire_tnt>, "banitem");
ItemStages.restrict(<item:thermal:ice_tnt>, "banitem");
ItemStages.restrict(<item:thermal:lightning_tnt>, "banitem");
ItemStages.restrict(<item:thermal:earth_tnt>, "banitem");
ItemStages.restrict(<item:thermal:ender_tnt>, "banitem");
ItemStages.restrict(<item:thermal:glowstone_tnt>, "banitem");
ItemStages.restrict(<item:thermal:redstone_tnt>, "banitem");
ItemStages.restrict(<item:thermal:slime_tnt>, "banitem");
ItemStages.restrict(<item:thermal:phyto_tnt>, "banitem");
ItemStages.restrict(<item:thermal:fire_tnt_minecart>, "banitem");
ItemStages.restrict(<item:thermal:ice_tnt_minecart>, "banitem");
ItemStages.restrict(<item:thermal:lightning_tnt_minecart>, "banitem");
ItemStages.restrict(<item:thermal:earth_tnt_minecart>, "banitem");
ItemStages.restrict(<item:thermal:ender_tnt_minecart>, "banitem");
ItemStages.restrict(<item:thermal:glowstone_tnt_minecart>, "banitem");
ItemStages.restrict(<item:thermal:redstone_tnt_minecart>, "banitem");
ItemStages.restrict(<item:thermal:slime_tnt_minecart>, "banitem");
ItemStages.restrict(<item:thermal:phyto_tnt_minecart>, "banitem");
ItemStages.restrict(<item:botania:mana_bomb>, "banitem");
ItemStages.restrict(<item:botania:mana_gun>, "banitem");
ItemStages.restrict(<item:tconstruct:seared_brick>, "banitem");
ItemStages.restrict(<item:pneumaticcraft:amadron_tablet>.withTag({shoppingCart: {}, "pneumaticcraft:air": 29052 as int}), "banitem"); 
ItemStages.restrict(<item:industrialforegoing:infinity_backpack>.withTag({CanCharge: 1 as byte, Special: 0 as byte, Selected: "POOR", Energy: 0 as long}), "banitem"); 
ItemStages.restrict(<item:industrialforegoing:infinity_saw>.withTag({CanCharge: 1 as byte, Special: 0 as byte, Selected: "POOR", Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}}), "banitem"); 
ItemStages.restrict(<item:industrialforegoing:infinity_hammer>.withTag({CanCharge: 1 as byte, Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}, Special: 0 as byte, Selected: "POOR", Beheading: 0 as int}), "banitem"); 
ItemStages.restrict(<item:industrialforegoing:infinity_trident>.withTag({CanCharge: 1 as byte, Riptide: 0 as int, Channeling: 0 as byte, Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}, Special: 0 as byte, Selected: "POOR", Loyalty: 0 as int}), "banitem"); 
ItemStages.restrict(<item:industrialforegoing:infinity_launcher>.withTag({CanCharge: 1 as byte, Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}, Special: 0 as byte, Selected: "POOR", Plunger: 0 as int}), "banitem"); 
ItemStages.restrict(<item:industrialforegoing:infinity_nuke>.withTag({CanCharge: 1 as byte, Special: 0 as byte, Selected: "POOR", Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}}), "banitem"); 
ItemStages.restrict(<item:industrialforegoing:infinity_drill>.withTag({CanCharge: 1 as byte, Special: 0 as byte, Selected: "POOR", Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}}), "banitem"); 
ItemStages.restrict(<item:ae2:portable_item_cell_1k>, "banitem");
ItemStages.restrict(<item:ae2:portable_item_cell_4k>, "banitem");
ItemStages.restrict(<item:ae2:portable_item_cell_16k>, "banitem");
ItemStages.restrict(<item:ae2:portable_item_cell_64k>, "banitem");
ItemStages.restrict(<item:ae2:portable_item_cell_256k>, "banitem");
ItemStages.restrict(<item:ae2:portable_fluid_cell_1k>, "banitem");
ItemStages.restrict(<item:ae2:portable_fluid_cell_4k>, "banitem");
ItemStages.restrict(<item:ae2:portable_fluid_cell_16k>, "banitem");
ItemStages.restrict(<item:ae2:portable_fluid_cell_64k>, "banitem");
ItemStages.restrict(<item:ae2:portable_fluid_cell_256k>, "banitem");
ItemStages.restrict(<item:ae2:matter_cannon>, "banitem");
ItemStages.restrict(<item:ae2:spatial_pylon>, "banitem");
ItemStages.restrict(<item:appmek:portable_chemical_storage_cell_1k>, "banitem");
ItemStages.restrict(<item:appmek:portable_chemical_storage_cell_4k>, "banitem");
ItemStages.restrict(<item:appmek:portable_chemical_storage_cell_16k>, "banitem");
ItemStages.restrict(<item:appmek:portable_chemical_storage_cell_64k>, "banitem");
ItemStages.restrict(<item:appmek:portable_chemical_storage_cell_256k>, "banitem");
ItemStages.restrict(<item:armourers_workshop:skin-library>, "banitem");
ItemStages.restrict(<item:armourers_workshop:skin-library-creative>, "banitem");
ItemStages.restrict(<item:armourers_workshop:skin-library-global>, "banitem");
ItemStages.restrict(<item:armourers_workshop:armourer>, "banitem");
ItemStages.restrict(<item:armourers_workshop:colour-mixer>, "banitem");
ItemStages.restrict(<item:armourers_workshop:advanced-skin-builder>, "banitem");
ItemStages.restrict(<item:tconstruct:copper_can>, "banitem");

mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:latex_processing_unit>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_cracked_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_cobble"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_paver"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_fancy_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_drain>.withTag({texture: "tconstruct:seared_triangle_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_cracked_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_cobble"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_paver"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_fancy_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_duct>.withTag({texture: "tconstruct:seared_triangle_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_cracked_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_cobble"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_paver"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_fancy_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_stone>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_cobble>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_paver>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_bricks>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_cracked_bricks>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_fancy_bricks>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_triangle_bricks>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_chute>.withTag({texture: "tconstruct:seared_triangle_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_stone>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:polished_scorched_stone>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_bricks>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_road>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:chiseled_scorched_bricks>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:scorched_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:polished_scorched_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:scorched_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:scorched_road"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_drain>.withTag({texture: "tconstruct:chiseled_scorched_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:scorched_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:polished_scorched_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:scorched_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:scorched_road"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_duct>.withTag({texture: "tconstruct:chiseled_scorched_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:scorched_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:polished_scorched_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:scorched_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:scorched_road"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_chute>.withTag({texture: "tconstruct:chiseled_scorched_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_fuel_tank>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_fuel_gauge>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_ingot_tank>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_ingot_gauge>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_lantern>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_faucet>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_channel>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_basin>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_table>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_fuel_tank>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_fuel_gauge>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_ingot_tank>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_ingot_gauge>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_lantern>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_faucet>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_channel>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_basin>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_table>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_cracked_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_cobble"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_paver"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_fancy_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:smeltery_controller>.withTag({texture: "tconstruct:seared_triangle_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:scorched_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:polished_scorched_stone"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:scorched_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:scorched_road"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:foundry_controller>.withTag({texture: "tconstruct:chiseled_scorched_bricks"}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_melter>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_heater>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_alloyer>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:satchel>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:exmachinis:flux_compactor>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:mekanism:basic_logistical_transporter>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:mekanism:advanced_logistical_transporter>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:mekanism:elite_logistical_transporter>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:mekanism:ultimate_logistical_transporter>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:quantum_link>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:quantum_ring>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:mechanical_dirt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:efln_ball>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:scorched_brick>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:explosive_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:fire_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:ice_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:lightning_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:earth_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:ender_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:glowstone_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:redstone_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:slime_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:phyto_grenade>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:fire_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:ice_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:lightning_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:earth_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:ender_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:glowstone_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:redstone_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:slime_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:phyto_tnt>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:fire_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:ice_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:lightning_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:earth_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:ender_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:glowstone_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:redstone_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:slime_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:thermal:phyto_tnt_minecart>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:botania:mana_bomb>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:botania:mana_gun>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:seared_brick>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:pneumaticcraft:amadron_tablet>.withTag({shoppingCart: {}, "pneumaticcraft:air": 29052 as int}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:infinity_backpack>.withTag({CanCharge: 1 as byte, Special: 0 as byte, Selected: "POOR", Energy: 0 as long}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:infinity_saw>.withTag({CanCharge: 1 as byte, Special: 0 as byte, Selected: "POOR", Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:infinity_hammer>.withTag({CanCharge: 1 as byte, Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}, Special: 0 as byte, Selected: "POOR", Beheading: 0 as int}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:infinity_trident>.withTag({CanCharge: 1 as byte, Riptide: 0 as int, Channeling: 0 as byte, Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}, Special: 0 as byte, Selected: "POOR", Loyalty: 0 as int}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:infinity_launcher>.withTag({CanCharge: 1 as byte, Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}, Special: 0 as byte, Selected: "POOR", Plunger: 0 as int}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:infinity_nuke>.withTag({CanCharge: 1 as byte, Special: 0 as byte, Selected: "POOR", Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:industrialforegoing:infinity_drill>.withTag({CanCharge: 1 as byte, Special: 0 as byte, Selected: "POOR", Energy: 0 as long, Fluid: {FluidName: "biofuel", Amount: 0 as int}}));
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_item_cell_1k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_item_cell_4k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_item_cell_16k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_item_cell_64k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_item_cell_256k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_fluid_cell_1k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_fluid_cell_4k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_fluid_cell_16k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_fluid_cell_64k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:portable_fluid_cell_256k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:matter_cannon>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:ae2:spatial_pylon>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:appmek:portable_chemical_storage_cell_1k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:appmek:portable_chemical_storage_cell_4k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:appmek:portable_chemical_storage_cell_16k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:appmek:portable_chemical_storage_cell_64k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:appmek:portable_chemical_storage_cell_256k>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:armourers_workshop:skin-library>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:armourers_workshop:skin-library-creative>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:armourers_workshop:skin-library-global>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:armourers_workshop:armourer>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:armourers_workshop:colour-mixer>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:armourers_workshop:advanced-skin-builder>);
mods.recipestages.Recipes.setRecipeStage("banitem", <item:tconstruct:copper_can>);