name: Deploy By WebDAV
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚗 Get Latest Code
      uses: actions/checkout@v3
    - name: 🤳 Deploy website
      uses: XPH0816/webdav-deploy-action@v0.3
      with:
        url: ${{ secrets.WEBDAV_URL }}
        username: ${{ secrets.WEBDAV_USERNAME }}
        password: ${{ secrets.WEBDAV_PASSWORD }}
        local: "./mcpatchv1/public"
        remote: "remote_directory/public"
